func_test/urls.py
from django.urls import path
from .views import home, confirmation

app_name = 'func_test'

urlpatterns = [
    path('', home, name='homepage'),
    path('confirm/', confirmation, name='confirm'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('func_test.urls'))
]

func_test/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
    name = models.CharField(max_length=20)
    status = models.CharField(max_length=100)
    

func_test/forms.py
from django import forms
from .models import Data

class DataForm (forms.ModelForm):
    class Meta: 
        model = Data
        fields = '__all__'

func_test/views.py
from django.shortcuts import render, redirect,reverse
from .forms import DataForm
from .models import Data
from django.views.generic import UpdateView
# Create your views here.


form_data = [{}]

def home(request):
    if request.method == "POST":
        form = DataForm(request.POST)
        name = request.POST.get("name")
        status = request.POST.get("status")
        form_data[0]['name'] = name
        form_data[0]['status'] = status
        if form.is_valid():
            return redirect("/confirm/")
        else:
            return redirect("/")
    else:
        return render (request, 'func_test/page.html',context={'datas' : Data.objects.all()} )

def confirmation(request):
    if request.method == "POST":
        form = DataForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else :
        return render(request, 'func_test/confirmation.html', {'form_data':form_data})

    

func_test/templates/func_test/confirmation.html
<!DOCTYPE html>
<html>
  <head>
    <title>story 7</title>
  </head>
<body>

{%for data in form_data%}
<form method="post">
    {% csrf_token %}
    <p>CONFIRMATION</p>
    <p>Are you sure you want to upload the following data?<br>
        Name: {{data.name}}<br>
        Status: {{data.status}}
    <input type="hidden" id="name" name="name" value="{{data.name}}"><br>
    <input type="hidden" id="status" name="status" value="{{data.status}}"><br><br>
    <input type="submit" value="Submit"><br>
    <a href='{% url "func_test:homepage"%}'>Cancel</a>
  </form> 
{%endfor%}

</body>
</html>

func_test/templates/func_test/page.html
<!DOCTYPE html>
<html>
  <head>
    <title>story 7</title>
  </head>
<body>


<form method="post">
  {% csrf_token %}
  <label for="name_data">Name: </label><br>
  <input type="text" id="name" name="name"><br>
  <label for="status_data">Status: </label><br>
  <input type="text" id="status" name="status"><br><br>
  <input type="submit" value="Submit">
</form> 

{%for data in datas%}
<p>{{data.name}}</p>
<p>{{data.status}}</p>
{%endfor%}



</body>
</html>